[[main]]
  identifier = "top"
  name = "top"
  url = "https://encr.jp/blog"
  weight = 1

[[main]]
  identifier = "categories"
  name = "categories"
  url = "categories"
  weight = 2

[[main]]
  identifier = "tags"
  name = "tags"
  url = "tags"
  weight = 3

[[main]]
  identifier = "service"
  name = "service"
  url = "https://encr.jp"
  weight = 4
